### ISSUE TITLE
Demo!

### ISSUE THREAD

**Issue by soufiane-fadil** [mayukh18/reco#1]
Dear all,

It could be great if there is a demo for this in the readme file.

I appreciate that, 
thanks

**Comment by mayukh18** [comment]
Added one for the SVD recommender. Will add the collaborative filtering one after some tweaks. :)

**Comment by soufiane-fadil** [comment]
Awesome !
i'll test it right now 👍 
Many thanks

**Comment by soufiane-fadil** [comment]
Oh, seams like recomenderd in reco is not recognized.
I got this issue, any idea about it ?

```
from reco.recommender import SVDRecommender
ImportError: No module named recommender
```

**Comment by mayukh18** [comment]
Have you installed it through pip? Better you uninstall and install it once. The current release is 0.1.12

**Comment by soufiane-fadil** [comment]
Yes i did, i followed the demo as it is, and i uninstalled it like you said and installed it again, but still have the same issue :/

**Comment by mayukh18** [comment]
There was indeed a glitch. The problem was somehow it wasn't getting caught or reproduced in my machine. It is fixed now. Reinstall and it should work fine. Thanks for pointing it out.

**Comment by soufiane-fadil** [comment]
It's working now, i'll try to test it on a datasource now :)

Many Thanks 👍
